### ISSUE TITLE
Is the data coming with a delay

### ISSUE THREAD

**Issue by mahmutoktay** [chrisgitrepo/fxcm#1]
Thank for this project. Regardless of the timeframe I choose, I get the candlestick data with a delay. For example, when I select the 15-minute candles, the last data incoming is at 18.00, but the current time is 18.47.

**Comment by chrisgitrepo** [comment]
The current candle is removed by default as it fluctuates the close price (not static). So in this case 18.30 will be removed as it represents the current price (not historical). If you need this current price, you can use markets() function.

**Comment by mahmutoktay** [comment]
Thanks for your answer. But it's time 18.47 and last candle incoming 18.00. Where are closed candle at 18.15, 18.30 and 18.45. three candles seem to be missing in total. Or I'm making a mistake somewhere. I want 15 minutes of candle data

**Comment by chrisgitrepo** [comment]
This library simply removes the live candle and returns the raw data from FXCM. I did face some delays with some currency pairs with FXCM. Unfortunately, this looks to be a feature with the FXCM API, perhaps you are using a demo api? Might be worth emailing FXCM as they might have an explanation. Sorry I cant be much more help.

**Comment by mahmutoktay** [comment]
Thanks for your interest
